apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: voice
resources:
  - pvc.yaml
  - cm-startup.yaml
  - deployment-vllm.yaml
  - service-vllm.yaml
  - deployment-wyoming.yaml
  - service-wyoming.yaml
