apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: home-assistant
  labels:
    app.kubernetes.io/name: minio
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 20Gi
