apiVersion: v1
imagePullSecrets:
- name: n8n-sa-dockercfg-k8gd6
kind: ServiceAccount
metadata:
  annotations:
    openshift.io/internal-registry-pull-secret-ref: n8n-sa-dockercfg-k8gd6
  name: n8n-sa
  namespace: n8n
secrets:
- name: n8n-sa-dockercfg-k8gd6
