apiVersion: v1
kind: ConfigMap
metadata:
  name: ha-addon-installer
  namespace: home-assistant
  labels:
    app.kubernetes.io/name: ha-addon-installer
    app.kubernetes.io/part-of: home-assistant
data:
  install.sh: |
    #!/bin/sh
    set -euo pipefail
    echo "[installer] Starting add-on installation..."
    BASE=/config/custom_components
    mkdir -p "$BASE"
    # tools
    apk add --no-cache curl unzip >/dev/null

    # Install HACS
    echo "[installer] Downloading HACS..."
    mkdir -p /tmp/hacs && cd /tmp/hacs
    curl -fsSL -o hacs.zip https://github.com/hacs/integration/releases/latest/download/hacs.zip
    unzip -o hacs.zip -d "$BASE" >/dev/null
    echo "[installer] HACS installed under $BASE/hacs"

    # Install OpenAI TTS custom integration
    echo "[installer] Downloading OpenAI TTS integration..."
    mkdir -p /tmp/openai_tts && cd /tmp/openai_tts
    curl -fsSL -o openai_tts.zip https://github.com/sfortis/openai_tts/archive/refs/heads/main.zip
    unzip -o openai_tts.zip -d /tmp/openai_tts >/dev/null
    # copy only custom_components/openai_tts
    src=$(find /tmp/openai_tts -type d -path "*/custom_components/openai_tts" | head -n1)
    mkdir -p "$BASE/openai_tts"
    cp -R "$src/." "$BASE/openai_tts/"
    echo "[installer] OpenAI TTS installed under $BASE/openai_tts"

    # permissions - make readable
    chmod -R a+rX /config/custom_components
    echo "[installer] Completed."
