apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-data
  namespace: voice
  labels:
    app.kubernetes.io/part-of: voice-assistant
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
