apiVersion: v1
kind: Service
metadata:
  name: wyoming-whisper-nodeport
  namespace: voice
  labels:
    app.kubernetes.io/name: wyoming-whisper
    app.kubernetes.io/part-of: voice-assistant
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: wyoming-whisper
  ports:
    - name: wyoming
      port: 10300
      targetPort: wyoming
      protocol: TCP
      # nodePort: 31030
