apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - operatorgroup.yaml
  - subscription.yaml
  - postgres.yaml
  - keycloak.yaml
  - realm.yaml
  - secret.yaml
  - oauth.yaml
  - clusterrolebinding.yaml
