apiVersion: v1
kind: Secret
metadata:
  name: keycloak-client-secret
  namespace: openshift-config
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/part-of: keycloak
type: Opaque
stringData:
  clientSecret: REPLACE_ME_WITH_OIDC_CLIENT_SECRET
